version: '3.6'

services:
 app:
   container_name: app
   build: .
   environment:
     PORT: 3000
     MONGO_URI: mongodb://mongo:27017/sample
   entrypoint: >-
     sh -c "npm install
     && npm start"
   ports:
     - "3000:3000"
   depends_on:
     - mongo
 mongo:
   image: mongo
   volumes:
     - ./data:/data/db
   ports:
   - "27017:27017"
